apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: external
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:5.4.3
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: external
spec:
  selector:
    app: zookeeper
  ports:
    - name: http
      port: 2181
      protocol: TCP
      targetPort: 2181
