version: "3.7"

services:

  mongodb:
    image: mongo:4.4.0
    container_name: mongodb
    env_file: .env-dev
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  # User Service
  user:
    container_name: user
    build:
      context: microservices/user/app
      dockerfile: Dockerfile-dev
    env_file: .env-dev
    environment:
      - MONGO_URL=mongodb
    ports:
      - "3000:3000"
    volumes:
      - "./microservices/user/app:/app"

  zookeeper:
    build: kafka/zookeeper
    ports:
        - "2181:2181"

  kafka:
    build: kafka/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


volumes:
  mongodb_data_container: