version: "3.7"

services:

  mongodb:
    image: mongo:4.4.0
    container_name: mongodb
    env_file: .env-dev
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    image: redis:6.0.6
    container_name: redis
    ports:
      - 6379:6379

  # User Service
  user:
    container_name: user
    build:
      context: microservices/user/app
      dockerfile: Dockerfile-dev
    env_file: .env-dev
    environment:
      - MONGO_URL=mongodb
      - REDIS_URL=redis
    ports:
      - "3000:3000"
    volumes:
      - "./microservices/user/app:/app"

volumes:
  mongodb_data_container:
