version: "3.7"

services:

  mongodb:
    image: mongo:4.4.0
    env_file: ./.env-dev
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  # User Service
  user:
    container_name: user
    build:
      context: microservices/user/app
      dockerfile: Dockerfile-dev
    env_file: ./.env-dev
    environment:
      - MONGO_URL=mongodb
    ports:
      - "3000:3000"
    volumes:
      - "./microservices/user/app:/app"

volumes:
  mongodb_data_container: