version: '3'

services:
  db:
    image: postgres:9-alpine
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql
  
  phppgadmin:
    image: dockage/phppgadmin:latest
    ports:
      - "8081:80"
    restart: unless-stopped
    environment: 
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=alexandrio
  
  backend:
    build: ./
    ports:
      - "420:8080"
    restart: unless-stopped
