apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: auth
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0.6
        imagePullPolicy: Always
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis
#   namespace: auth
# spec:
#   selector:
#     app: redis
#   ports:
#     - name: http
#       port: 6379
#       protocol: TCP
#       targetPort: 6379