---
openapi: 3.0.2
info:
  description: "Documentation for the Alexandrio's microsecervice REST API\n\n
                <b>You can find the documentation of the microservices in these pages:</b>\n\n
                <a href=\"{{ .Auth }}\" class=\"sc-fzooss hmVskR\">Auth</a>
                <a href=\"{{ .User }}\" class=\"sc-fzooss hmVskR\">User</a>
                <a href=\"{{ .Library }}\" class=\"sc-fzooss hmVskR\">Library</a>
                <a href=\"{{ .Media }}\" class=\"sc-fzooss hmVskR\">Media</a>"
  version: v1
  title: Alexandrio Documentation
paths:
  /ping:
    get:
      description: Check whether or not a service is running
      responses:
        '200':
          description: The service is running
      servers:
        - url: //service.alexandrio.cloud
          description: Production server
        - url: //service.preprod.alexandrio.cloud
          description: Preprod server
      tags:
        - PING
