apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: external
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.0
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            mountPath: /data/db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: url
          - name: MONGO_INITDB_DATABASE
            value: admin

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongo-data


---
apiVersion: v1
kind: Service
metadata:
  namespace: external
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      nodePort: 30000
  type: NodePort
status:
  loadBalancer: {}
