# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import metadata_pb2 as metadata__pb2


class MetadataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Metadata = channel.unary_unary(
                '/metadata.Metadata/Metadata',
                request_serializer=metadata__pb2.MetadataRequest.SerializeToString,
                response_deserializer=metadata__pb2.MetadataReply.FromString,
                )


class MetadataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Metadata(self, request, context):
        """Used to check a JWT and retrieve the corresponding user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.Metadata,
                    request_deserializer=metadata__pb2.MetadataRequest.FromString,
                    response_serializer=metadata__pb2.MetadataReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metadata.Metadata', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Metadata(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metadata.Metadata/Metadata',
            metadata__pb2.MetadataRequest.SerializeToString,
            metadata__pb2.MetadataReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
