kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend
subjects:
  - kind: Group
    name: backend
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: backend
  apiGroup: rbac.authorization.k8s.io