apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: media
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/alexandr-io/backend/media:latest-preprod
          imagePullPolicy: Always
          env:
            - name: MEDIA_PATH
              value: "/media/"
            - name: MEDIA_URI
              value: "file"

            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: url

            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka
                  key: ADVERTISED_HOST_NAME
            - name: KAFKA_ADVERTISED_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka
                  key: KAFKA_ADVERTISED_PORT
            - name: KAFKA_URL
              value: "$(KAFKA_ADVERTISED_HOST_NAME):$(KAFKA_ADVERTISED_PORT)"

          volumeMounts:
            - name: data
              mountPath: /media

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: media-data

      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: media
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
