FROM python:3.9

ARG microservice
ARG path=microservices/${microservice}/app

WORKDIR /app
COPY ./${path} .
COPY ./grpc/${microservice}/*.py ./
RUN pip install --only-binary ":all:" requests grpcio protobuf 
CMD python ./server.py
