FROM golang:1.15.0

RUN GO111MODULE=on go get github.com/cosmtrek/air@v1.15.1

RUN GO111MODULE=on go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
RUN export PATH="$PATH:$(go env GOPATH)/bin"

ARG microservice
ARG path=microservices/${microservice}/app

WORKDIR /${path}

COPY ./${path}/go.mod ./${path}/go.sum ./${path}/data*/go.mod* ./${path}/data*/go.sum* ./
RUN ls -la / && make
COPY grpc/go.mod /grpc/
RUN go mod download
CMD ["air"]
