---
- hosts: all

  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install requirement packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
      state: present
      update_cache: no