---
- hosts: all

  tasks:
    - name: Copy Cert folder to the server
      copy:
        src: ../../kubernetes/cert
        dest: /cert
        owner: alexandrio
        group: alexandrio

    - name: Create backend ClusterRole
      shell: "kubectl apply -f /kubernetes/cert/backend_cluster_role.yaml"
      become: yes
      become_method: su
      become_user: alexandrio

    - name: Create backend ClusterRoleBinding
      shell: "kubectl apply -f /kubernetes/cert/backend_cluster_role_binding.yaml"
      become: yes
      become_method: su
      become_user: alexandrio