---
- hosts: all

  tasks:

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'

  - name: Install docker-ce and docker-compose
    apt:
      name:
        - docker-ce
        - docker-compose
      state: present
      update_cache: no

  - name: Run and enable docker
    service:
      name: docker
      state: started
      enabled: true