---
- hosts: all

  tasks:

  - name: Install latest kubectl
    snap:
      name: kubectl
      classic: yes

  - name: Install kubeadm
    snap:
      name: kubeadm
      classic: yes
  
  - name: Install kubelet
    snap:
      name: kubelet
      classic: yes
