---
- hosts: all

  tasks:

  - name: Copy Traefik config files from the host to the serveur
    copy:
      src: ../../kubernetes/traefik
      dest: /kubernetes
      owner: alexandrio
      group: alexandrio

  - name: Define the Ressources used by Traefik on the k8s cluster
    shell: "kubectl apply -f /kubernetes/traefik/Resources.yaml"
    become: yes
    become_method: su
    become_user: alexandrio

  - name: Create the Traefik app
    shell: "kubectl apply -f /kubernetes/traefik/Traefik.yaml"
    become: yes
    become_method: su
    become_user: alexandrio

  - name: Deploy external application
    shell: "/kubernetes/app-deployment.sh external"
    become: yes
    become_method: su
    become_user: alexandrio
