apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: external
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: confluentinc/cp-server:5.4.3
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka
                  key: KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: kafka
                  key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
---
apiVersion: v1
kind: Service
metadata:
  namespace: external
  name: broker
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 9092
      nodePort: 30001
  type: NodePort
status:
  loadBalancer: { }
