info:
  description: |-
    Documentation for the Alexandrio's microsecervice REST API

     <b>You can find the documentation of the microservices in these pages:</b>

     <a href="http://localhost:4000/auth" class="sc-fzooss hmVskR">Auth</a> <a href="http://localhost:4000/user" class="sc-fzooss hmVskR">User</a> <a href="http://localhost:4000/library" class="sc-fzooss hmVskR">Library</a> <a href="http://localhost:4000/media" class="sc-fzooss hmVskR">Media</a>
  title: Alexandrio Documentation
  version: v1
openapi: 3.0.2
paths:
  /ping:
    get:
      description: Check whether or not a service is running
      responses:
        "200":
          description: The service is running
      servers:
      - description: Production server
        url: //service.alexandrio.cloud
      - description: Preprod server
        url: //service.preprod.alexandrio.cloud
      tags:
      - PING
