apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: user
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ghcr.io/alexandr-io/backend/user:latest
        imagePullPolicy: Always
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: url

          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password

          - name: DISCORD_FEEDBACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: discord-webhook-secret
                  key: webhookurl

          - name: AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: microservices-dns
                key: AUTH_URL
          - name: EMAIL_URL
            valueFrom:
              configMapKeyRef:
                name: microservices-dns
                key: EMAIL_URL
          - name: GRPC_PORT
            valueFrom:
              configMapKeyRef:
                name: grpc-port
                key: PORT
          - name: REDIS_URL
            value: redis
          - name: REDIS_PORT
            value: "6379"
          - name: USER_URI
            value: https://user.alexandrio.cloud

      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: user
spec:
  selector:
    app: api
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: grpc
      port: 5051
      protocol: TCP
      targetPort: 5051
