name: Build and push preprod images CI
# This workflow is triggered on tag push finishing with '-preprod'
on:
  push:
    tags:
      - v*-preprod

jobs:
  build-and-push-user:
    name: Docker Build User and push image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push User Docker image with tag number
        # Official docker action: https://github.com/docker/build-push-action
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          # github.repository -> alexandr-io/backend
          # https://github.com/docker/build-push-action/pull/14/files/d1c5c2f87bcd65b263d72ea6b1861bb25cbbcda5#r429877166
          repository: ${{github.repository}}/user
          tag_with_ref: true
          path: microservices/user/app
          push: true

      - name: Build and push User Docker image with tag latest-preprod
        # Official docker action: https://github.com/docker/build-push-action
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          # github.repository -> alexandr-io/backend
          # https://github.com/docker/build-push-action/pull/14/files/d1c5c2f87bcd65b263d72ea6b1861bb25cbbcda5#r429877166
          repository: ${{github.repository}}/user
          tags: latest-preprod
          path: microservices/user/app
          push: true

      - name: Deploy or redeploy user app
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST_PREPROD }}
          user: ${{ secrets.HOST_PREPROD_USERNAME }}
          pass: ${{ secrets.HOST_PREPROD_PASSWORD }}
          script: /kubernetes/app-deployment.sh user

  build-and-push-auth:
    name: Docker Build Auth and push image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Auth Docker image with tag number
        # Official docker action: https://github.com/docker/build-push-action
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          # github.repository -> alexandr-io/backend
          # https://github.com/docker/build-push-action/pull/14/files/d1c5c2f87bcd65b263d72ea6b1861bb25cbbcda5#r429877166
          repository: ${{github.repository}}/auth
          tag_with_ref: true
          path: microservices/auth/app
          push: true

      - name: Build and push Auth Docker image with tag latest-preprod
        # Official docker action: https://github.com/docker/build-push-action
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          # github.repository -> alexandr-io/backend
          # https://github.com/docker/build-push-action/pull/14/files/d1c5c2f87bcd65b263d72ea6b1861bb25cbbcda5#r429877166
          repository: ${{github.repository}}/auth
          tags: latest-preprod
          path: microservices/auth/app
          push: true

      - name: Deploy or redeploy auth app
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST_PREPROD }}
          user: ${{ secrets.HOST_PREPROD_USERNAME }}
          pass: ${{ secrets.HOST_PREPROD_PASSWORD }}
          script: /kubernetes/app-deployment.sh auth