name: Backend code checker CI
# This workflow is triggered on pull requests.
on: pull_request

jobs:
  fmt:
    name: Run code checks
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run go fmt
      - name: Run gofmt
        uses: grandcolline/golang-github-actions@v1.1.0 # https://github.com/grandcolline/golang-github-actions
        with:
          run: fmt
          token: ${{ secrets.GITHUB_TOKEN }}

      # Check imports
      # Using https://godoc.org/golang.org/x/tools/cmd/goimports
      - name: Check imports
        uses: grandcolline/golang-github-actions@v1.1.0 # https://github.com/grandcolline/golang-github-actions
        with:
          run: imports
          token: ${{ secrets.GITHUB_TOKEN }}

      # Lint
      # Using https://github.com/golang/lint
      - name: Lint
        uses: grandcolline/golang-github-actions@v1.1.0 # https://github.com/grandcolline/golang-github-actions
        with:
          run: lint
          token: ${{ secrets.GITHUB_TOKEN }}