# This workflow is triggered on tag push finishing with '-preprod'

name: CD preproduction doc

on:
  push:
    tags:
      - v*-preprod

jobs:
  build-push-preprod:
    name: Build push image doc
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: AlexandrioCloud
          password: ${{ secrets.ACCESS_TOKEN_GITHUB }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: builder

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.11.0
        with:
          images: ghcr.io/${{ github.repository }}/doc
          tag-custom: "latest-preprod"
          tag-latest: false

      - name: Build and push doc Docker image
        uses: docker/build-push-action@v2.2.2
        with:
          builder: ${{ steps.builder.outputs.name }}
          context: .
          file: ./dockerfiles/Dockerfile-doc
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true

      - name: Deploy or redeploy doc app
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST_PREPROD }}
          user: ${{ secrets.HOST_PREPROD_USERNAME }}
          pass: ${{ secrets.HOST_PREPROD_PASSWORD }}
          script: /kubernetes/app-deployment.sh doc
