name: Email service build CI
# This workflow is triggered on pushes to the /microservices/email/app/ directory.
# The workflow does not trigger on main and pre-prod branch
on:
  push:
    paths:
      - 'microservices/email/app/**'
    branches-ignore:
      - master

jobs:
  build-email:
    name: Docker Build Email
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Email Docker image
        # Official docker action: https://github.com/docker/build-push-action
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./dockerfiles/Dockerfile
          build-args: |
            microservice=email
          push: false
