name: Email CD prod
# This workflow is triggered on tag push
on:
  push:
    tags-ignore:
      - 'v*-*'

jobs:
  build-email-push-prod:
    name: Build push image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: AlexandrioCloud
          password: ${{ secrets.ACCESS_TOKEN_GITHUB }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: builder

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.11.0
        with:
          images: ghcr.io/${{github.repository}}/email
          tag-latest: true

      - name: Build and push Email Docker image
        uses: docker/build-push-action@v2.2.2
        with:
          builder: ${{ steps.builder.outputs.name }}
          context: .
          file: ./dockerfiles/Dockerfile
          build-args: |
            microservice=email
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true

      - name: Deploy or redeploy email app
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST_PROD }}
          user: ${{ secrets.HOST_PROD_USERNAME }}
          pass: ${{ secrets.HOST_PROD_PASSWORD }}
          script: /kubernetes/app-deployment.sh email
